### PR TITLE
Spectrum

### PR DESCRIPTION
**Pull request by alejoe91**
- implement `plot_spectrum` and `plot_spectrogram`

### CODE REVIEW

**Comment by alejoe91** [comment]
@ferchaure something like this should work

**Comment by samuelgarcia** [comment]
Is it in the scope of spikeinterface ?

I don't really like matplotlib magic function for spectrum stuff.
I prefer to use scipy.signal one and then plot with imshow even if it is much work.
We can have more control on parameters.

**Comment by alejoe91** [comment]
This was a request from @ferchaure . I think it's nice to give the possibility to quickly plot the spectrum within SI. No?

**Comment by ferchaure** [comment]
Nice, thanks @alejoe91.

It could be better if the NFFT parameter is accessible, otherwise we won't see the peaks in 50 or 60Hz in raw data. Probably with that the functions will be good enough to show some useful things .

> Is it in the scope of spikeinterface ?

If SI open, filter and sort war data, it have to allow some minimum checks for each step.

**Comment by alejoe91** [comment]
Added nftt param + tests.

@samuelgarcia I think it's in the scope. Users can use scipy if they want. This could be useful :)

**Comment by samuelgarcia** [comment]
OK for me.
Spectrum is usefull for checking.

Just wanted to advocatde that si scope is spike sorting and general ephy tools box :)

**Comment by alejoe91** [comment]
@samuelgarcia any idea why the test is failing? seems it can't import plot_spectrum and plot_spectrogram

**Comment by alejoe91** [comment]
ahhhh spikecomparison requires spikewidgets!!! I think it should be reversed. We can make widgets for GT study

**Comment by samuelgarcia** [comment]
My idea was to make figure and report generation inside spiekcompraison.study.
So this is why it was in this order.
In my mind we already discuss that no ? :)
Why does this cause problem for spectrum ?

**Comment by alejoe91** [comment]
@samuelgarcia the problem is that I installed spikecomparison before spikeiwdgets in travis, so it installed the pip version.

For the time being I removed spikewidgets as dependency as it's not used yet. 
Why not having GroundTruthStudy plots in spikewidgets? It could also be its own module!

This way we stick to the scope of each package, with spikewidget being the only one for visualization.
I know we discussed it before, but I like that all packages have a very defined scope :)

**Pull request merged**
